import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/responsive.css";
import Header from "@/components/Header";
import { Category, FooterDetail } from "@/lib/types";
import { getAllCategories } from "@/lib/api/category";
import { getFooterDetail } from "@/lib/api/footer";
import Footer from "@/components/Footer";
import { WishlistProvider } from "@/context/WishlistContext";
import ScrollRestoration from "./ScrollRestoration";
import ScrollToTop from "./ScrollToTop";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories: Category[] = await getAllCategories();
  const footerDetail: FooterDetail | null = await getFooterDetail();
  return (
    <html lang="en">
      <WishlistProvider>
        <body className={montserrat.className}>
          <ScrollRestoration />
          <ScrollToTop />
          <Header categories={categories} footerDetail={footerDetail} />
          <main>{children}</main>
          <Footer categories={categories} footerDetail={footerDetail} />
        </body>
      </WishlistProvider>
    </html>
  );
}
